FROM centos:7

RUN yum install -y centos-release-scl-rh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
  yum install -y devtoolset-9-gcc devtoolset-9-gcc-c++ git zlib-devel p7zip p7zip-plugins python3 patch curl && \
  ln -s /opt/rh/devtoolset-9/root/usr/bin/* /usr/local/bin

RUN curl -Lo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.2.1/yq_linux_amd64 && chmod +x /usr/local/bin/yq

ARG GRAALVM_ARCH=linux-amd64
ARG GRAALVM_VERSION=20.0.0
ARG JAVA_VERSION=java11
ARG GRAALVM_PKG=https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$JAVA_VERSION-$GRAALVM_ARCH-$GRAALVM_VERSION.tar.gz

ENV JAVA_HOME=/opt/graalvm-ce-$JAVA_VERSION-$GRAALVM_VERSION
ENV PATH=$PATH:$JAVA_HOME/bin

RUN mkdir -p "${JAVA_HOME}" && curl -L "${GRAALVM_PKG}" | tar --strip-components=1 -xzvC "${JAVA_HOME}"
